### ISSUE TITLE
feat001: Rework Annotations

### ISSUE THREAD

**Issue by umj95** [umj95/Glarean#2]
Interlinear annotations have so far been encoded in the following manner:
```xml
preceding text <add type="super" xml:id="add_id">annotation</add> associated text.
```
Until now, this text was only parsed to HTML when the appropriate flag in the URL was set. The corresponding `<span class="addition superscript"></span>` element was then placed as an interlinear glosse, mirroring the source, with the following CSS:
```css
addition.superscript {
    display: inline-block;
    position: absolute;
    transform: translate(0, -55%);
    font-size: var(--comment-fontsize);
    text-decoration: none;
}
```
This solution is not optimal in terms of legibility and leads to problems with line breaks. I think that it would be preferable to render these annotations not between the lines but to the side (maybe the left to distinguish them from the marginal notes in the original). They could be connected to connected to their anchors in the text with highlighting, superscript numerals, etc. A tooltip could further explain their relation.
